### ISSUE TITLE
Rules / How to play modal for first time viewers.

### ISSUE THREAD

**Issue by jamesurobertson** [jamesurobertson/trumple#3]
I'd like to add a Rules / How to play modal for first time viewers, similar to the real games. Attached is a screenshot of Wordle's implementation:

![Wordle Modal](https://user-images.githubusercontent.com/21094319/167230265-1de23287-732b-4e9c-abea-507d9f838a61.png)

**Comment by matthewbub** [comment]
Is there have a mock? I'd be happy to build it out 🙂

**Comment by jamesurobertson** [comment]
@yeahmat Just the screenshot posted above of what Wordle's implementation looks like. I'm wanting something similar, doesn't need to look like that.

**Comment by matthewbub** [comment]
Sure i can get started on that. Estimating 3hrs to build and test, should have it ready by tomorrow morning.👍  

I will plan on making it look similar the screen shot of Wordle while incorporating your current theme. 🎨 

**Question** Should we use localStorage to determine if a user is new? If not, do you have and suggestions for a preferred alternative?

**Comment by jamesurobertson** [comment]
Yep, localStorage. There is some commented out code in Game.js incorporating localstorage for the current game state. I was waiting on a statistics page / reset before using it but you can follow that same pattern. 

Thank you for working on this issue!
